function validateStage06Config(cfg)
%VALIDATESTAGE06CONFIG Validate guarded native Stage06 config.

required = {'caseId','heading_offsets_deg','h_grid_km','i_grid_deg','P_grid','T_grid', ...
    'F_fixed','Tmax_s','Ts_s','Tw_s','maxHeadingsGuard','maxDesignsGuard'};
for k = 1:numel(required)
    assert(isfield(cfg, required{k}), 'ttube:stage06:InvalidConfig', ...
        'Missing Stage06 config field: %s', required{k});
end
offsets = cfg.heading_offsets_deg(:).';
assert(~isempty(offsets) && all(isfinite(offsets)), ...
    'ttube:stage06:InvalidHeadingScope', 'heading_offsets_deg must be finite and nonempty.');
assert(numel(offsets) <= cfg.maxHeadingsGuard, ...
    'ttube:stage06:InvalidHeadingScope', 'Heading count exceeds maxHeadingsGuard.');
assert(~isfield(cfg,'useParallel') || ~cfg.useParallel, ...
    'ttube:stage06:InvalidConfig', 'Stage06 native profiles disable parallel execution.');
designCount = numel(cfg.h_grid_km) * numel(cfg.i_grid_deg) * numel(cfg.P_grid) * numel(cfg.T_grid);
assert(designCount <= cfg.maxDesignsGuard, ...
    'ttube:stage06:GridTooLarge', 'Stage06 design grid exceeds maxDesignsGuard.');
assert(designCount * numel(offsets) <= cfg.maxDesignHeadingEvalsGuard, ...
    'ttube:stage06:GridTooLarge', 'Stage06 design-heading product exceeds guard.');
assert(cfg.Ts_s >= 5 && cfg.Tmax_s <= 180, ...
    'ttube:stage06:InvalidConfig', 'Stage06 safe profiles require Ts_s >= 5 and Tmax_s <= 180.');
end
